on:
  push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # 安装 mdBook
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v2

      # 安装 go
      - name: Setup Go
        uses: actions/setup-go@v5

      # 安装 mdbook-mergecells
      - name: Install mdbook-mergecells
        run: |
          go install github.com/E79180/mdbook-mergecells@latest

      # 构建文档
      - name: Build doc
        run: |
          export PATH=$PATH:$HOME/go/bin
          mdbook build -d public

      # 部署
      - name: Deploy to CFWorker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 4.20.0
